"""initial_schema

Revision ID: 319e76f0e99b
Revises: 
Create Date: 2026-04-04 00:43:48.472292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319e76f0e99b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('novel_title', sa.String(length=100), nullable=False, comment='原著名称'),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active | archived'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('template_code', sa.String(length=100), nullable=False, comment='模板业务ID，如 CHAR_XIAO_YAN_v2_battle_stance'),
    sa.Column('template_type', sa.String(length=20), nullable=False, comment='模板类型：character / location / effect / scene_style'),
    sa.Column('version', sa.String(length=10), nullable=False, comment='版本号，如 v1.0 / v1.3'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否为该 template_code 的当前最优版本'),
    sa.Column('base_prompt', sa.Text(), nullable=False, comment='基础提示词（英文）'),
    sa.Column('style_suffix', sa.Text(), nullable=True, comment="风格后缀，如 'donghua animation style, cinematic lighting'"),
    sa.Column('negative_prompt', sa.Text(), nullable=True, comment='负向提示词'),
    sa.Column('model_params', sa.JSON(), nullable=True, comment="生成参数，如 {cfg_scale: 7, steps: 30, sampler: 'dpm++'}"),
    sa.Column('lora_config', sa.JSON(), nullable=True, comment="LoRA 配置，如 {model: 'xiao_yan_v2', weight: 0.8}"),
    sa.Column('result_rating', sa.Float(), nullable=True, comment='该版本平均评分（0-10）'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('change_reason', sa.Text(), nullable=True, comment='相比上一版本的改动原因'),
    sa.Column('issue_description', sa.Text(), nullable=True, comment='发现的问题描述（如：面部偏日式风格）'),
    sa.Column('fix_description', sa.Text(), nullable=True, comment='修复方法描述'),
    sa.Column('parent_template_id', sa.Integer(), nullable=True, comment='上一版本的模板ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('char_code', sa.String(length=30), nullable=False, comment='角色业务ID，如 CHAR_XIAO_YAN'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('name_aliases', sa.JSON(), nullable=False, comment="别名列表，如 ['小炎', '药尊']"),
    sa.Column('consistent_features', sa.JSON(), nullable=True, comment="跨版本不变的固定特征，如 {eyes: '漆黑色瞳仁', skin: '小麦色'}"),
    sa.Column('expression_guide', sa.JSON(), nullable=True, comment="各情绪状态的表情描述，如 {anger: '眉心微蹙...', determination: '眼神直视...'}"),
    sa.Column('action_guide', sa.JSON(), nullable=True, comment="常见动作姿态描述，如 {standing_default: '...', battle_stance: '...'}"),
    sa.Column('relationships', sa.JSON(), nullable=True, comment="角色关系描述，如 {CHAR_YAO_LAO: {relation: '师徒', desc: '核心导师'}}"),
    sa.Column('role_description', sa.Text(), nullable=True, comment='角色在故事中的地位和作用简述'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('char_code')
    )
    op.create_index(op.f('ix_characters_project_id'), 'characters', ['project_id'], unique=False)
    op.create_table('scenes',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scene_code', sa.String(length=20), nullable=False, comment='业务ID，如 DQCK_001'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('novel_chapter_start', sa.String(length=50), nullable=True, comment='起始章节'),
    sa.Column('novel_chapter_end', sa.String(length=50), nullable=True, comment='结束章节'),
    sa.Column('novel_excerpt', sa.Text(), nullable=True, comment='原著关键段落摘录'),
    sa.Column('scene_types', sa.JSON(), nullable=False, comment='片段类型列表：战斗高光/情感高潮/成长节点/世界观展开/反转时刻'),
    sa.Column('priority', sa.String(length=2), nullable=False, comment='S/A/B/C'),
    sa.Column('score_dramatic_tension', sa.Integer(), nullable=True, comment='戏剧张力'),
    sa.Column('score_visual_potential', sa.Integer(), nullable=True, comment='视觉化潜力'),
    sa.Column('score_emotional_resonance', sa.Integer(), nullable=True, comment='情感共鸣度'),
    sa.Column('score_narrative_importance', sa.Integer(), nullable=True, comment='叙事重要性'),
    sa.Column('score_audience_familiarity', sa.Integer(), nullable=True, comment='粉丝熟知度'),
    sa.Column('score_total', sa.Integer(), nullable=True, comment='总分（满50）'),
    sa.Column('character_ids', sa.JSON(), nullable=False),
    sa.Column('estimated_duration_sec', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft | scored | in_production | completed'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_code')
    )
    op.create_index(op.f('ix_scenes_project_id'), 'scenes', ['project_id'], unique=False)
    op.create_table('character_versions',
    sa.Column('character_id', sa.Integer(), nullable=False, comment='所属角色ID'),
    sa.Column('version_code', sa.String(length=30), nullable=False, comment='版本标识，如 v1_teen / v2_post_training'),
    sa.Column('label', sa.String(length=100), nullable=False, comment="版本显示名称，如 '少年期（15-16岁）'"),
    sa.Column('applicable_chapter_start', sa.String(length=50), nullable=True, comment="该版本适用的起始章节，如 '第1章'"),
    sa.Column('applicable_chapter_end', sa.String(length=50), nullable=True, comment="该版本适用的结束章节，如 '第50章'"),
    sa.Column('age_description', sa.String(length=50), nullable=True, comment='年龄描述'),
    sa.Column('height_cm', sa.Integer(), nullable=True, comment='身高（厘米）'),
    sa.Column('build_description', sa.Text(), nullable=True, comment="体型描述，如 '瘦削，肩膀略窄'"),
    sa.Column('face_description', sa.Text(), nullable=True, comment='面部描述'),
    sa.Column('hair_description', sa.Text(), nullable=True, comment='发型描述'),
    sa.Column('costumes', sa.JSON(), nullable=True, comment="服装配置，如 {default: '白色粗布长袍...', battle: '白袍轻微战损'}"),
    sa.Column('dou_qi_color', sa.String(length=10), nullable=True, comment='斗气颜色HEX值，如 #FFB830'),
    sa.Column('dou_qi_level', sa.String(length=20), nullable=True, comment='对应境界，如 斗灵/斗王/斗皇'),
    sa.Column('key_features', sa.JSON(), nullable=False, comment="标志性细节，如 ['左耳佩戴玉坠', '右手无名指疤痕']"),
    sa.Column('reference_image_urls', sa.JSON(), nullable=False, comment='该版本的参考图URL列表'),
    sa.Column('base_image_prompt', sa.Text(), nullable=True, comment='该版本的图像生成基础提示词（英文）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_versions_character_id'), 'character_versions', ['character_id'], unique=False)
    op.create_table('storyboards',
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('emotion_curve', sa.JSON(), nullable=True, comment="情感弧线数据，格式：[{time_sec: 0, intensity: 2, label: '压抑开场'}, ...]"),
    sa.Column('narrative_notes', sa.Text(), nullable=True, comment='叙事设计备注'),
    sa.Column('pacing_ratio', sa.JSON(), nullable=True, comment='节奏比例，格式：{buildup: 30, climax: 40, resolution: 30}'),
    sa.Column('total_duration_sec', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft | generating | review | approved'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboards_scene_id'), 'storyboards', ['scene_id'], unique=True)
    op.create_table('shots',
    sa.Column('storyboard_id', sa.Integer(), nullable=False),
    sa.Column('shot_code', sa.String(length=30), nullable=False, comment='业务ID，如 DQCK_001_S003'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='在分镜脚本中的顺序'),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('camera', sa.JSON(), nullable=True, comment='摄像机配置：{shot_type, angle, movement, focal_length, depth_of_field}'),
    sa.Column('composition', sa.JSON(), nullable=True, comment='构图描述：{subject_position, foreground, midground, background, leading_lines}'),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('char_version_id', sa.Integer(), nullable=True),
    sa.Column('character_action', sa.Text(), nullable=True, comment='角色动作描述'),
    sa.Column('character_expression', sa.Text(), nullable=True, comment='表情描述'),
    sa.Column('character_emotion_intensity', sa.Integer(), nullable=True, comment='情绪强度 1-10'),
    sa.Column('character_sfx', sa.JSON(), nullable=True, comment='角色特效：{dou_qi_color, dou_qi_pattern, aura_intensity, particle_effects}'),
    sa.Column('location_id', sa.String(length=50), nullable=True, comment='地点标识，如 LOC_YUNLAN_SQUARE'),
    sa.Column('environment', sa.JSON(), nullable=True, comment='环境配置：{time_of_day, weather, lighting, atmosphere}'),
    sa.Column('dialogue_character', sa.String(length=50), nullable=True),
    sa.Column('dialogue_text', sa.Text(), nullable=True),
    sa.Column('dialogue_delivery', sa.JSON(), nullable=True, comment='台词情感参数：{tone, pace, pause_positions, emphasis_words, emotion_tags}'),
    sa.Column('sound_design', sa.JSON(), nullable=True, comment='音效设计：{ambient, sfx_list, music}'),
    sa.Column('transition_in', sa.String(length=50), nullable=True, comment='入场转场类型'),
    sa.Column('transition_out', sa.String(length=50), nullable=True, comment='出场转场类型'),
    sa.Column('transition_notes', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=False, comment='依赖的其他镜头列表：[{type, depends_on_shot_id, dependency_detail}]'),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('style_preset', sa.String(length=100), nullable=True),
    sa.Column('qc_character_consistency', sa.Boolean(), nullable=False),
    sa.Column('qc_lighting_match', sa.Boolean(), nullable=False),
    sa.Column('qc_action_continuity', sa.Boolean(), nullable=False),
    sa.Column('qc_approved', sa.Boolean(), nullable=False),
    sa.Column('qc_score', sa.Integer(), nullable=True, comment='整体评分 0-100'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft | generating | review | approved | rejected'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['char_version_id'], ['character_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_code')
    )
    op.create_index(op.f('ix_shots_character_id'), 'shots', ['character_id'], unique=False)
    op.create_index(op.f('ix_shots_storyboard_id'), 'shots', ['storyboard_id'], unique=False)
    op.create_table('assets',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('shot_id', sa.Integer(), nullable=True, comment='关联镜头ID，全局素材（如角色参考图）可为空'),
    sa.Column('asset_code', sa.String(length=100), nullable=False, comment='素材业务ID，遵循命名规范，如 CHAR_XIAO_YAN_v2_portrait_front_normal'),
    sa.Column('asset_type', sa.String(length=20), nullable=False, comment='素材类型：image / video / audio / reference'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='文件存储路径或URL'),
    sa.Column('file_format', sa.String(length=10), nullable=True, comment='文件格式，如 png / mp4 / wav'),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('width', sa.Integer(), nullable=True, comment='宽度（像素）'),
    sa.Column('height', sa.Integer(), nullable=True, comment='高度（像素）'),
    sa.Column('duration_sec', sa.Float(), nullable=True, comment='视频/音频时长（秒）'),
    sa.Column('source', sa.String(length=30), nullable=False, comment='素材来源：generated（AI生成）/ uploaded（手动上传）'),
    sa.Column('generator', sa.String(length=50), nullable=True, comment='生成工具，如 stable_diffusion / midjourney / runway / kling'),
    sa.Column('tags', sa.JSON(), nullable=False, comment="标签列表，便于检索，如 ['萧炎', 'v2', '战斗状态']"),
    sa.Column('description', sa.Text(), nullable=True, comment='素材说明'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号，同一镜头重新生成时递增'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否为当前使用版本'),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True, comment='上一版本的素材ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_code')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_shot_id'), 'assets', ['shot_id'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('shot_id', sa.Integer(), nullable=True, comment='关联镜头ID，场景级任务（如分镜脚本批量生成）可为空'),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True, comment='Celery 任务ID，用于查询任务状态'),
    sa.Column('task_type', sa.String(length=30), nullable=False, comment='任务类型：image_generation / video_generation / storyboard_generation / audio_generation / qc_check'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='任务状态：pending / running / success / failed / cancelled'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度百分比 0-100'),
    sa.Column('input_params', sa.JSON(), nullable=True, comment='任务输入参数快照（提示词、模型参数等），便于重试和审计'),
    sa.Column('result_asset_id', sa.Integer(), nullable=True, comment='生成成功后关联的素材ID'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='任务开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='任务完成时间'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='已重试次数'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='最大重试次数'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index(op.f('ix_generation_tasks_shot_id'), 'generation_tasks', ['shot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_tasks_shot_id'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index(op.f('ix_assets_shot_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_shots_storyboard_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_character_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_storyboards_scene_id'), table_name='storyboards')
    op.drop_table('storyboards')
    op.drop_index(op.f('ix_character_versions_character_id'), table_name='character_versions')
    op.drop_table('character_versions')
    op.drop_index(op.f('ix_scenes_project_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_characters_project_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_table('prompt_templates')
    op.drop_table('projects')
    # ### end Alembic commands ###
