"""add char_image_refs and location_image_refs to shots

Revision ID: 6c5286c1ae4a
Revises: k8l9m0n1o2p3
Create Date: 2026-04-06 12:44:17.588095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c5286c1ae4a'
down_revision: Union[str, Sequence[str], None] = 'k8l9m0n1o2p3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'project_id',
               existing_type=sa.INTEGER(),
               comment='Project ID',
               existing_comment='所属项目ID',
               existing_nullable=False)
    op.alter_column('assets', 'shot_id',
               existing_type=sa.INTEGER(),
               comment='Related shot ID',
               existing_comment='关联镜头ID，全局素材（如角色参考图）可为空',
               existing_nullable=True)
    op.alter_column('assets', 'location_id',
               existing_type=sa.INTEGER(),
               comment='Related location ID',
               existing_nullable=True)
    op.alter_column('assets', 'location_version_id',
               existing_type=sa.INTEGER(),
               comment='Related location version ID',
               existing_nullable=True)
    op.alter_column('assets', 'character_id',
               existing_type=sa.INTEGER(),
               comment='Related character ID',
               existing_nullable=True)
    op.alter_column('assets', 'asset_code',
               existing_type=sa.VARCHAR(length=100),
               comment='Business asset code',
               existing_comment='素材业务ID，遵循命名规范，如 CHAR_XIAO_YAN_v2_portrait_front_normal',
               existing_nullable=False)
    op.alter_column('assets', 'asset_type',
               existing_type=sa.VARCHAR(length=20),
               comment='image / video / audio / reference',
               existing_comment='素材类型：image / video / audio / reference',
               existing_nullable=False)
    op.alter_column('assets', 'file_url',
               existing_type=sa.TEXT(),
               comment='File URL',
               existing_comment='文件存储路径或URL',
               existing_nullable=False)
    op.alter_column('assets', 'file_format',
               existing_type=sa.VARCHAR(length=10),
               comment='File format',
               existing_comment='文件格式，如 png / mp4 / wav',
               existing_nullable=True)
    op.alter_column('assets', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               comment='File size in bytes',
               existing_comment='文件大小（字节）',
               existing_nullable=True)
    op.alter_column('assets', 'width',
               existing_type=sa.INTEGER(),
               comment='Width in pixels',
               existing_comment='宽度（像素）',
               existing_nullable=True)
    op.alter_column('assets', 'height',
               existing_type=sa.INTEGER(),
               comment='Height in pixels',
               existing_comment='高度（像素）',
               existing_nullable=True)
    op.alter_column('assets', 'duration_sec',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Duration in seconds',
               existing_comment='视频/音频时长（秒）',
               existing_nullable=True)
    op.alter_column('assets', 'source',
               existing_type=sa.VARCHAR(length=30),
               comment='generated / uploaded',
               existing_comment='素材来源：generated（AI生成）/ uploaded（手动上传）',
               existing_nullable=False)
    op.alter_column('assets', 'generator',
               existing_type=sa.VARCHAR(length=50),
               comment='Generator or tool name',
               existing_comment='生成工具，如 stable_diffusion / midjourney / runway / kling',
               existing_nullable=True)
    op.alter_column('assets', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Search tags',
               existing_comment="标签列表，便于检索，如 ['萧炎', 'v2', '战斗状态']",
               existing_nullable=False)
    op.alter_column('assets', 'description',
               existing_type=sa.TEXT(),
               comment='Description',
               existing_comment='素材说明',
               existing_nullable=True)
    op.alter_column('assets', 'version',
               existing_type=sa.INTEGER(),
               comment='Asset version number',
               existing_comment='版本号，同一镜头重新生成时递增',
               existing_nullable=False)
    op.alter_column('assets', 'is_current',
               existing_type=sa.BOOLEAN(),
               comment='Whether this is the current version',
               existing_comment='是否为当前使用版本',
               existing_nullable=False)
    op.alter_column('assets', 'parent_asset_id',
               existing_type=sa.INTEGER(),
               comment='Previous asset version ID',
               existing_comment='上一版本的素材ID',
               existing_nullable=True)
    op.drop_column('assets', 'status')
    op.drop_column('assets', 'error_message')
    op.alter_column('character_versions', 'three_view_url',
               existing_type=sa.VARCHAR(length=500),
               comment='三视图URL（包含正面、侧面、背面的单张图片）',
               existing_nullable=True)
    op.alter_column('character_versions', 'state_images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="状态图片URL字典，如 {anger: 'url', skill_release: 'url', happy: 'url'}",
               existing_nullable=True)
    op.alter_column('location_versions', 'location_id',
               existing_type=sa.INTEGER(),
               comment='所属场景ID',
               existing_nullable=False)
    op.alter_column('location_versions', 'version_code',
               existing_type=sa.VARCHAR(length=30),
               comment="版本标识，如 'default' / 'night' / 'battle_damaged' / 'rain'",
               existing_comment='版本标识',
               existing_nullable=False)
    op.alter_column('location_versions', 'label',
               existing_type=sa.VARCHAR(length=100),
               comment="版本显示名称，如 '夜晚' / '战斗损毁' / '雨天'",
               existing_comment='版本显示名称',
               existing_nullable=False)
    op.alter_column('location_versions', 'description',
               existing_type=sa.TEXT(),
               comment='该变体的特殊描述，与主场景描述叠加',
               existing_comment='该变体的特殊描述',
               existing_nullable=True)
    op.alter_column('location_versions', 'time_of_day',
               existing_type=sa.VARCHAR(length=20),
               comment='时间：dawn / day / dusk / night',
               existing_comment='时间：dawn/day/dusk/night',
               existing_nullable=True)
    op.alter_column('location_versions', 'weather',
               existing_type=sa.VARCHAR(length=30),
               comment='天气：clear / cloudy / rain / snow / fog / storm',
               existing_comment='天气',
               existing_nullable=True)
    op.alter_column('location_versions', 'additional_elements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="额外元素，如 ['战火痕迹', '破碎的石柱']",
               existing_comment='额外元素',
               existing_nullable=False)
    op.alter_column('location_versions', 'removed_elements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="移除的元素，如 ['石碑']（被摧毁）",
               existing_comment='移除的元素',
               existing_nullable=False)
    op.alter_column('location_versions', 'full_prompt',
               existing_type=sa.TEXT(),
               comment='完整提示词（如与基础差异大，可直接覆盖）',
               existing_comment='完整提示词',
               existing_nullable=True)
    op.alter_column('location_versions', 'applicable_scene_codes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='适用的片段code列表（可选，用于推荐）',
               existing_comment='适用的片段code列表',
               existing_nullable=False)
    op.alter_column('location_versions', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('location_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('location_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('location_versions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='软删除标记。True 表示已删除，业务查询必须过滤此字段',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('location_versions', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='软删除时间（UTC），is_deleted 为 True 时记录',
               existing_nullable=True)
    op.alter_column('locations', 'project_id',
               existing_type=sa.INTEGER(),
               comment='所属项目ID',
               existing_nullable=False)
    op.alter_column('locations', 'loc_code',
               existing_type=sa.VARCHAR(length=50),
               comment='业务ID，如 LOC_YUNLAN_SQUARE、LOC_XIAO_FAMILY_HALL',
               existing_comment='业务ID，如 LOC_YUNLAN_SQUARE',
               existing_nullable=False)
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="场景名称，如 '云岚宗广场'",
               existing_comment='场景名称',
               existing_nullable=False)
    op.alter_column('locations', 'aliases',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="别名列表，如 ['云岚宗山门', '云岚宗主殿前']",
               existing_comment='别名列表',
               existing_nullable=False)
    op.alter_column('locations', 'location_type',
               existing_type=sa.VARCHAR(length=20),
               comment='场景类型：indoor(室内) / outdoor(室外) / fantasy(玄幻场景) / mixed(混合)',
               existing_comment='场景类型：indoor/outdoor/fantasy/mixed',
               existing_nullable=False)
    op.alter_column('locations', 'domain',
               existing_type=sa.VARCHAR(length=50),
               comment="所属势力/领域，如 '云岚宗' / '萧家' / '沙漠'",
               existing_comment='所属势力/领域',
               existing_nullable=True)
    op.alter_column('locations', 'architectural_style',
               existing_type=sa.VARCHAR(length=100),
               comment="建筑风格，如 '中国古风' / '异域沙漠' / '玄幻仙宫'",
               existing_comment='建筑风格',
               existing_nullable=True)
    op.alter_column('locations', 'key_elements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="标志性元素，如 ['九十九级白玉台阶', '巨大石碑', '云雾缭绕']",
               existing_comment='标志性元素',
               existing_nullable=False)
    op.alter_column('locations', 'default_atmosphere',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='默认氛围配置：{weather, lighting, mood, color_tone}',
               existing_comment='默认氛围配置',
               existing_nullable=True)
    op.alter_column('locations', 'time_variants',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="时间变体描述：{dawn: '...', day: '...', dusk: '...', night: '...'}",
               existing_comment='时间变体描述',
               existing_nullable=True)
    op.alter_column('locations', 'base_background_prompt',
               existing_type=sa.TEXT(),
               comment='背景生成基础提示词（英文），变体提示词在此基础上修改',
               existing_comment='背景生成基础提示词',
               existing_nullable=True)
    op.alter_column('locations', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="标签，如 ['云岚宗', '正道', '广场', '室外']",
               existing_comment='标签',
               existing_nullable=False)
    op.alter_column('locations', 'usage_count',
               existing_type=sa.INTEGER(),
               comment='被引用次数（统计用）',
               existing_comment='被引用次数',
               existing_nullable=False)
    op.alter_column('locations', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='软删除标记。True 表示已删除，业务查询必须过滤此字段',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('locations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='软删除时间（UTC），is_deleted 为 True 时记录',
               existing_nullable=True)
    op.alter_column('scenes', 'scene_code',
               existing_type=sa.VARCHAR(length=20),
               comment='业务ID，如 P1_EP001',
               existing_comment='业务ID，如 DQCK_001',
               existing_nullable=False)
    op.alter_column('scenes', 'synopsis',
               existing_type=sa.TEXT(),
               comment='200-400字剧情概述',
               existing_comment='剧情概述，100-300字',
               existing_nullable=True)
    op.alter_column('scenes', 'key_events',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='关键剧情节点列表')
    op.alter_column('scenes', 'characters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='角色名列表')
    op.alter_column('scenes', 'character_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='关联角色ID列表',
               existing_nullable=False)
    op.alter_column('scenes', 'visual_highlights',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='视觉亮点列表')
    op.alter_column('scenes', 'scene_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='场景类型标签',
               existing_comment='片段类型列表：战斗高光/情感高潮/成长节点/世界观展开/反转时刻',
               existing_nullable=False)
    op.alter_column('scenes', 'estimated_duration_sec',
               existing_type=sa.INTEGER(),
               comment='预估时长（秒）',
               existing_nullable=True)
    op.alter_column('scenes', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='draft | in_production | completed',
               existing_comment='draft | scored | in_production | completed',
               existing_nullable=False)
    op.alter_column('shot_groups', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment="可读名称，如'战斗连段'",
               existing_comment='可读名称',
               existing_nullable=True)
    op.alter_column('shot_groups', 'total_duration_sec',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成员分镜时长之和（须 ≤ 15s）',
               existing_comment='成员分镜时长之和',
               existing_nullable=True)
    op.alter_column('shot_groups', 'video_url',
               existing_type=sa.TEXT(),
               comment='合并视频 URL（OSS 永久链接）',
               existing_comment='合并视频 URL',
               existing_nullable=True)
    op.alter_column('shot_groups', 'plan_intent',
               existing_type=sa.TEXT(),
               comment='Phase 1 规划的叙事意图（narrative_intent 字段）',
               existing_comment='Narrative intent from Phase 1 Planner AI',
               existing_nullable=True)
    op.alter_column('shot_groups', 'phase2_task_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Phase 2 Creator AI 对应的 Celery 任务ID（预留）',
               existing_comment='Celery task ID for this group Phase 2 Creator task (reserved)',
               existing_nullable=True)
    op.alter_column('shot_groups', 'image_references',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='参考图列表：[{char_version_id, url, label}]',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('shot_groups', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shot_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shot_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shot_groups', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='软删除标记。True 表示已删除，业务查询必须过滤此字段',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('shot_groups', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='软删除时间（UTC），is_deleted 为 True 时记录',
               existing_nullable=True)
    op.drop_index(op.f('ix_shot_groups_group_code'), table_name='shot_groups')
    op.create_index(op.f('ix_shot_groups_is_deleted'), 'shot_groups', ['is_deleted'], unique=False)
    op.add_column('shots', sa.Column('char_image_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True, server_default=sa.text("'[]'::json"), comment='角色参考图：[{char_version_id, name, urls}]'))
    op.add_column('shots', sa.Column('location_image_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True, server_default=sa.text("'[]'::json"), comment='场景参考图：[{location_version_id, location_id, name, urls}]'))
    # Backfill existing NULL rows with empty arrays
    op.execute("UPDATE shots SET char_image_refs = '[]'::json WHERE char_image_refs IS NULL")
    op.execute("UPDATE shots SET location_image_refs = '[]'::json WHERE location_image_refs IS NULL")
    # Now make NOT NULL
    op.alter_column('shots', 'char_image_refs', nullable=False)
    op.alter_column('shots', 'location_image_refs', nullable=False)
    op.alter_column('shots', 'shot_group_id',
               existing_type=sa.INTEGER(),
               comment='所属分镜组 ID，NULL 表示独立分镜',
               existing_comment='所属分镜组 ID',
               existing_nullable=True)
    op.alter_column('shots', 'char_version_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               comment='角色版本ID列表，如 [1, 3, 5]')
    op.alter_column('shots', 'characters_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='多角色配置：[{char_version_id, action, expression, emotion_intensity, sfx}]',
               existing_nullable=True)
    op.alter_column('shots', 'environment',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='环境配置：{location_id, location_version_id, time_of_day, weather, lighting, atmosphere}',
               existing_comment='环境配置：{time_of_day, weather, lighting, atmosphere}',
               existing_nullable=True)
    op.alter_column('shots', 'video_url',
               existing_type=sa.TEXT(),
               comment='生成的视频 URL',
               existing_nullable=True)
    op.alter_column('storyboards', 'plan_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Phase 1 Planner AI 输出的分组规划数据',
               existing_comment='Phase 1 Planner AI output — group-level plan',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storyboards', 'plan_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Phase 1 Planner AI output — group-level plan',
               existing_comment='Phase 1 Planner AI 输出的分组规划数据',
               existing_nullable=True)
    op.alter_column('shots', 'video_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='生成的视频 URL',
               existing_nullable=True)
    op.alter_column('shots', 'environment',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='环境配置：{time_of_day, weather, lighting, atmosphere}',
               existing_comment='环境配置：{location_id, location_version_id, time_of_day, weather, lighting, atmosphere}',
               existing_nullable=True)
    op.alter_column('shots', 'characters_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='多角色配置：[{char_version_id, action, expression, emotion_intensity, sfx}]',
               existing_nullable=True)
    op.alter_column('shots', 'char_version_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               comment=None,
               existing_comment='角色版本ID列表，如 [1, 3, 5]')
    op.alter_column('shots', 'shot_group_id',
               existing_type=sa.INTEGER(),
               comment='所属分镜组 ID',
               existing_comment='所属分镜组 ID，NULL 表示独立分镜',
               existing_nullable=True)
    op.drop_column('shots', 'location_image_refs')
    op.drop_column('shots', 'char_image_refs')
    op.drop_index(op.f('ix_shot_groups_is_deleted'), table_name='shot_groups')
    op.create_index(op.f('ix_shot_groups_group_code'), 'shot_groups', ['group_code'], unique=False)
    op.alter_column('shot_groups', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='软删除时间（UTC），is_deleted 为 True 时记录',
               existing_nullable=True)
    op.alter_column('shot_groups', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='软删除标记。True 表示已删除，业务查询必须过滤此字段',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('shot_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shot_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shot_groups', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shot_groups', 'image_references',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='参考图列表：[{char_version_id, url, label}]',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('shot_groups', 'phase2_task_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Celery task ID for this group Phase 2 Creator task (reserved)',
               existing_comment='Phase 2 Creator AI 对应的 Celery 任务ID（预留）',
               existing_nullable=True)
    op.alter_column('shot_groups', 'plan_intent',
               existing_type=sa.TEXT(),
               comment='Narrative intent from Phase 1 Planner AI',
               existing_comment='Phase 1 规划的叙事意图（narrative_intent 字段）',
               existing_nullable=True)
    op.alter_column('shot_groups', 'video_url',
               existing_type=sa.TEXT(),
               comment='合并视频 URL',
               existing_comment='合并视频 URL（OSS 永久链接）',
               existing_nullable=True)
    op.alter_column('shot_groups', 'total_duration_sec',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成员分镜时长之和',
               existing_comment='成员分镜时长之和（须 ≤ 15s）',
               existing_nullable=True)
    op.alter_column('shot_groups', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='可读名称',
               existing_comment="可读名称，如'战斗连段'",
               existing_nullable=True)
    op.alter_column('scenes', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='draft | scored | in_production | completed',
               existing_comment='draft | in_production | completed',
               existing_nullable=False)
    op.alter_column('scenes', 'estimated_duration_sec',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='预估时长（秒）',
               existing_nullable=True)
    op.alter_column('scenes', 'scene_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='片段类型列表：战斗高光/情感高潮/成长节点/世界观展开/反转时刻',
               existing_comment='场景类型标签',
               existing_nullable=False)
    op.alter_column('scenes', 'visual_highlights',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='视觉亮点列表')
    op.alter_column('scenes', 'character_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='关联角色ID列表',
               existing_nullable=False)
    op.alter_column('scenes', 'characters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='角色名列表')
    op.alter_column('scenes', 'key_events',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='关键剧情节点列表')
    op.alter_column('scenes', 'synopsis',
               existing_type=sa.TEXT(),
               comment='剧情概述，100-300字',
               existing_comment='200-400字剧情概述',
               existing_nullable=True)
    op.alter_column('scenes', 'scene_code',
               existing_type=sa.VARCHAR(length=20),
               comment='业务ID，如 DQCK_001',
               existing_comment='业务ID，如 P1_EP001',
               existing_nullable=False)
    op.alter_column('locations', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='软删除时间（UTC），is_deleted 为 True 时记录',
               existing_nullable=True)
    op.alter_column('locations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='软删除标记。True 表示已删除，业务查询必须过滤此字段',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('locations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('locations', 'usage_count',
               existing_type=sa.INTEGER(),
               comment='被引用次数',
               existing_comment='被引用次数（统计用）',
               existing_nullable=False)
    op.alter_column('locations', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='标签',
               existing_comment="标签，如 ['云岚宗', '正道', '广场', '室外']",
               existing_nullable=False)
    op.alter_column('locations', 'base_background_prompt',
               existing_type=sa.TEXT(),
               comment='背景生成基础提示词',
               existing_comment='背景生成基础提示词（英文），变体提示词在此基础上修改',
               existing_nullable=True)
    op.alter_column('locations', 'time_variants',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='时间变体描述',
               existing_comment="时间变体描述：{dawn: '...', day: '...', dusk: '...', night: '...'}",
               existing_nullable=True)
    op.alter_column('locations', 'default_atmosphere',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='默认氛围配置',
               existing_comment='默认氛围配置：{weather, lighting, mood, color_tone}',
               existing_nullable=True)
    op.alter_column('locations', 'key_elements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='标志性元素',
               existing_comment="标志性元素，如 ['九十九级白玉台阶', '巨大石碑', '云雾缭绕']",
               existing_nullable=False)
    op.alter_column('locations', 'architectural_style',
               existing_type=sa.VARCHAR(length=100),
               comment='建筑风格',
               existing_comment="建筑风格，如 '中国古风' / '异域沙漠' / '玄幻仙宫'",
               existing_nullable=True)
    op.alter_column('locations', 'domain',
               existing_type=sa.VARCHAR(length=50),
               comment='所属势力/领域',
               existing_comment="所属势力/领域，如 '云岚宗' / '萧家' / '沙漠'",
               existing_nullable=True)
    op.alter_column('locations', 'location_type',
               existing_type=sa.VARCHAR(length=20),
               comment='场景类型：indoor/outdoor/fantasy/mixed',
               existing_comment='场景类型：indoor(室内) / outdoor(室外) / fantasy(玄幻场景) / mixed(混合)',
               existing_nullable=False)
    op.alter_column('locations', 'aliases',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='别名列表',
               existing_comment="别名列表，如 ['云岚宗山门', '云岚宗主殿前']",
               existing_nullable=False)
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='场景名称',
               existing_comment="场景名称，如 '云岚宗广场'",
               existing_nullable=False)
    op.alter_column('locations', 'loc_code',
               existing_type=sa.VARCHAR(length=50),
               comment='业务ID，如 LOC_YUNLAN_SQUARE',
               existing_comment='业务ID，如 LOC_YUNLAN_SQUARE、LOC_XIAO_FAMILY_HALL',
               existing_nullable=False)
    op.alter_column('locations', 'project_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属项目ID',
               existing_nullable=False)
    op.alter_column('location_versions', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='软删除时间（UTC），is_deleted 为 True 时记录',
               existing_nullable=True)
    op.alter_column('location_versions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='软删除标记。True 表示已删除，业务查询必须过滤此字段',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('location_versions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('location_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('location_versions', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('location_versions', 'applicable_scene_codes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='适用的片段code列表',
               existing_comment='适用的片段code列表（可选，用于推荐）',
               existing_nullable=False)
    op.alter_column('location_versions', 'full_prompt',
               existing_type=sa.TEXT(),
               comment='完整提示词',
               existing_comment='完整提示词（如与基础差异大，可直接覆盖）',
               existing_nullable=True)
    op.alter_column('location_versions', 'removed_elements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='移除的元素',
               existing_comment="移除的元素，如 ['石碑']（被摧毁）",
               existing_nullable=False)
    op.alter_column('location_versions', 'additional_elements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='额外元素',
               existing_comment="额外元素，如 ['战火痕迹', '破碎的石柱']",
               existing_nullable=False)
    op.alter_column('location_versions', 'weather',
               existing_type=sa.VARCHAR(length=30),
               comment='天气',
               existing_comment='天气：clear / cloudy / rain / snow / fog / storm',
               existing_nullable=True)
    op.alter_column('location_versions', 'time_of_day',
               existing_type=sa.VARCHAR(length=20),
               comment='时间：dawn/day/dusk/night',
               existing_comment='时间：dawn / day / dusk / night',
               existing_nullable=True)
    op.alter_column('location_versions', 'description',
               existing_type=sa.TEXT(),
               comment='该变体的特殊描述',
               existing_comment='该变体的特殊描述，与主场景描述叠加',
               existing_nullable=True)
    op.alter_column('location_versions', 'label',
               existing_type=sa.VARCHAR(length=100),
               comment='版本显示名称',
               existing_comment="版本显示名称，如 '夜晚' / '战斗损毁' / '雨天'",
               existing_nullable=False)
    op.alter_column('location_versions', 'version_code',
               existing_type=sa.VARCHAR(length=30),
               comment='版本标识',
               existing_comment="版本标识，如 'default' / 'night' / 'battle_damaged' / 'rain'",
               existing_nullable=False)
    op.alter_column('location_versions', 'location_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属场景ID',
               existing_nullable=False)
    op.alter_column('character_versions', 'state_images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment="状态图片URL字典，如 {anger: 'url', skill_release: 'url', happy: 'url'}",
               existing_nullable=True)
    op.alter_column('character_versions', 'three_view_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='三视图URL（包含正面、侧面、背面的单张图片）',
               existing_nullable=True)
    op.add_column('assets', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='错误信息（status=failed 时）'))
    op.add_column('assets', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'completed'::character varying"), autoincrement=False, nullable=False, comment='素材状态：pending（生成中）/ completed（已完成）/ failed（失败）'))
    op.alter_column('assets', 'parent_asset_id',
               existing_type=sa.INTEGER(),
               comment='上一版本的素材ID',
               existing_comment='Previous asset version ID',
               existing_nullable=True)
    op.alter_column('assets', 'is_current',
               existing_type=sa.BOOLEAN(),
               comment='是否为当前使用版本',
               existing_comment='Whether this is the current version',
               existing_nullable=False)
    op.alter_column('assets', 'version',
               existing_type=sa.INTEGER(),
               comment='版本号，同一镜头重新生成时递增',
               existing_comment='Asset version number',
               existing_nullable=False)
    op.alter_column('assets', 'description',
               existing_type=sa.TEXT(),
               comment='素材说明',
               existing_comment='Description',
               existing_nullable=True)
    op.alter_column('assets', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="标签列表，便于检索，如 ['萧炎', 'v2', '战斗状态']",
               existing_comment='Search tags',
               existing_nullable=False)
    op.alter_column('assets', 'generator',
               existing_type=sa.VARCHAR(length=50),
               comment='生成工具，如 stable_diffusion / midjourney / runway / kling',
               existing_comment='Generator or tool name',
               existing_nullable=True)
    op.alter_column('assets', 'source',
               existing_type=sa.VARCHAR(length=30),
               comment='素材来源：generated（AI生成）/ uploaded（手动上传）',
               existing_comment='generated / uploaded',
               existing_nullable=False)
    op.alter_column('assets', 'duration_sec',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='视频/音频时长（秒）',
               existing_comment='Duration in seconds',
               existing_nullable=True)
    op.alter_column('assets', 'height',
               existing_type=sa.INTEGER(),
               comment='高度（像素）',
               existing_comment='Height in pixels',
               existing_nullable=True)
    op.alter_column('assets', 'width',
               existing_type=sa.INTEGER(),
               comment='宽度（像素）',
               existing_comment='Width in pixels',
               existing_nullable=True)
    op.alter_column('assets', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               comment='文件大小（字节）',
               existing_comment='File size in bytes',
               existing_nullable=True)
    op.alter_column('assets', 'file_format',
               existing_type=sa.VARCHAR(length=10),
               comment='文件格式，如 png / mp4 / wav',
               existing_comment='File format',
               existing_nullable=True)
    op.alter_column('assets', 'file_url',
               existing_type=sa.TEXT(),
               comment='文件存储路径或URL',
               existing_comment='File URL',
               existing_nullable=False)
    op.alter_column('assets', 'asset_type',
               existing_type=sa.VARCHAR(length=20),
               comment='素材类型：image / video / audio / reference',
               existing_comment='image / video / audio / reference',
               existing_nullable=False)
    op.alter_column('assets', 'asset_code',
               existing_type=sa.VARCHAR(length=100),
               comment='素材业务ID，遵循命名规范，如 CHAR_XIAO_YAN_v2_portrait_front_normal',
               existing_comment='Business asset code',
               existing_nullable=False)
    op.alter_column('assets', 'character_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Related character ID',
               existing_nullable=True)
    op.alter_column('assets', 'location_version_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Related location version ID',
               existing_nullable=True)
    op.alter_column('assets', 'location_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Related location ID',
               existing_nullable=True)
    op.alter_column('assets', 'shot_id',
               existing_type=sa.INTEGER(),
               comment='关联镜头ID，全局素材（如角色参考图）可为空',
               existing_comment='Related shot ID',
               existing_nullable=True)
    op.alter_column('assets', 'project_id',
               existing_type=sa.INTEGER(),
               comment='所属项目ID',
               existing_comment='Project ID',
               existing_nullable=False)
    # ### end Alembic commands ###
