"""add_soft_delete_to_all_tables

Revision ID: d0d59dd25b30
Revises: ed5c756b9728
Create Date: 2026-04-04 01:02:50.272383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0d59dd25b30'
down_revision: Union[str, Sequence[str], None] = 'ed5c756b9728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('assets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('assets', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_assets_is_deleted'), 'assets', ['is_deleted'], unique=False)
    op.add_column('character_versions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('character_versions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('character_versions', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('character_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_character_versions_is_deleted'), 'character_versions', ['is_deleted'], unique=False)
    op.add_column('characters', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('characters', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('characters', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_characters_is_deleted'), 'characters', ['is_deleted'], unique=False)
    op.add_column('generation_tasks', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('generation_tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('generation_tasks', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('generation_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_generation_tasks_is_deleted'), 'generation_tasks', ['is_deleted'], unique=False)
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('projects', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.add_column('prompt_templates', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('prompt_templates', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('prompt_templates', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_prompt_templates_is_deleted'), 'prompt_templates', ['is_deleted'], unique=False)
    op.add_column('scenes', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('scenes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('scenes', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('scenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_scenes_is_deleted'), 'scenes', ['is_deleted'], unique=False)
    op.add_column('shots', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('shots', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('shots', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_shots_is_deleted'), 'shots', ['is_deleted'], unique=False)
    op.add_column('storyboards', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('storyboards', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('storyboards', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('storyboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('storyboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_storyboards_is_deleted'), 'storyboards', ['is_deleted'], unique=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_storyboards_is_deleted'), table_name='storyboards')
    op.alter_column('storyboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('storyboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('storyboards', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('storyboards', 'deleted_at')
    op.drop_column('storyboards', 'is_deleted')
    op.drop_index(op.f('ix_shots_is_deleted'), table_name='shots')
    op.alter_column('shots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shots', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('shots', 'deleted_at')
    op.drop_column('shots', 'is_deleted')
    op.drop_index(op.f('ix_scenes_is_deleted'), table_name='scenes')
    op.alter_column('scenes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenes', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('scenes', 'deleted_at')
    op.drop_column('scenes', 'is_deleted')
    op.drop_index(op.f('ix_prompt_templates_is_deleted'), table_name='prompt_templates')
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('prompt_templates', 'deleted_at')
    op.drop_column('prompt_templates', 'is_deleted')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'is_deleted')
    op.drop_index(op.f('ix_generation_tasks_is_deleted'), table_name='generation_tasks')
    op.alter_column('generation_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_tasks', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('generation_tasks', 'deleted_at')
    op.drop_column('generation_tasks', 'is_deleted')
    op.drop_index(op.f('ix_characters_is_deleted'), table_name='characters')
    op.alter_column('characters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('characters', 'deleted_at')
    op.drop_column('characters', 'is_deleted')
    op.drop_index(op.f('ix_character_versions_is_deleted'), table_name='character_versions')
    op.alter_column('character_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_versions', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('character_versions', 'deleted_at')
    op.drop_column('character_versions', 'is_deleted')
    op.drop_index(op.f('ix_assets_is_deleted'), table_name='assets')
    op.alter_column('assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键，自增整数',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('assets', 'deleted_at')
    op.drop_column('assets', 'is_deleted')
    # ### end Alembic commands ###
