"""add_conversations_and_messages

Revision ID: e948853f5a72
Revises: d0d59dd25b30
Create Date: 2026-04-04 11:57:22.239860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e948853f5a72'
down_revision: Union[str, Sequence[str], None] = 'd0d59dd25b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题，如「第01集 - 药老现身」'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active | draft_ready | confirmed'),
    sa.Column('latest_outline', sa.JSON(), nullable=True, comment='最新 EpisodeOutline JSON，确认后同步到 Scene'),
    sa.Column('scene_id', sa.Integer(), nullable=True, comment='确认后创建的分集 Scene ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键，自增整数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_is_deleted'), 'conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversations_scene_id'), 'conversations', ['scene_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='所属会话'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user | assistant | system'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='text           — 普通对话消息\noutline_draft  — AI 生成的剧本大纲草稿（含 outline_data）\noutline_confirmed — 用户最终确认的大纲（只有一条）\nsystem_action  — 系统操作记录'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息正文（Markdown 格式）'),
    sa.Column('outline_data', sa.JSON(), nullable=True, comment='EpisodeOutline JSON，仅 outline_* 类型消息有值'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='消息序号（升序），用于保证排序稳定'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键，自增整数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC），每次 UPDATE 自动刷新'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='软删除标记。True 表示已删除，业务查询必须过滤此字段'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC），is_deleted 为 True 时记录'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_is_deleted'), 'messages', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_is_deleted'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_scene_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_deleted'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
