"""add_users_and_project_owner

Revision ID: ed5c756b9728
Revises: 319e76f0e99b
Create Date: 2026-04-04 01:01:00.038284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5c756b9728'
down_revision: Union[str, Sequence[str], None] = '319e76f0e99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='用户邮箱，作为登录账号'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名，用于显示'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt 哈希后的密码，绝不存储明文'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账号是否启用，停用后无法登录'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否为超级管理员，可访问所有用户的数据'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像图片URL'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('projects', sa.Column('owner_id', sa.Integer(), nullable=False, comment='项目所有者的用户ID，所有查询均需校验此字段实现用户隔离'))
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='项目名称',
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               comment='项目描述',
               existing_nullable=True)
    op.alter_column('projects', 'cover_image_url',
               existing_type=sa.VARCHAR(length=500),
               comment='封面图URL',
               existing_nullable=True)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.alter_column('projects', 'cover_image_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='封面图URL',
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='项目描述',
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='项目名称',
               existing_nullable=False)
    op.drop_column('projects', 'owner_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
