"""drop_char_image_refs_location_image_refs_char_version_ids_from_shots

Revision ID: ff631c82aeb7
Revises: p8q9r0s1t2u3
Create Date: 2026-04-08 23:02:40.406710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff631c82aeb7'
down_revision: Union[str, Sequence[str], None] = 'p8q9r0s1t2u3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shot_groups', 'end_frame_description',
               existing_type=sa.TEXT(),
               comment='Phase 3 导演输出的本组终态描述（中文），供下一组生成时参考',
               existing_comment='Phase 3 导演输出的本组终态描述（中文），供下一组参考',
               existing_nullable=True)
    op.alter_column('shots', 'reference_images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='用户选择的参考图：[{url, label, name, char_version_id?, location_id?}]',
               existing_comment='用户选择的参考图：[{url, label, name, ...}]',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('shots', 'char_version_ids')
    op.drop_column('shots', 'location_image_refs')
    op.drop_column('shots', 'char_image_refs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shots', sa.Column('char_image_refs', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False, comment='角色参考图：[{char_version_id, name, urls}]'))
    op.add_column('shots', sa.Column('location_image_refs', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False, comment='场景参考图：[{location_version_id, location_id, name, urls}]'))
    op.add_column('shots', sa.Column('char_version_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='角色版本ID列表，如 [1, 3, 5]'))
    op.alter_column('shots', 'reference_images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='用户选择的参考图：[{url, label, name, ...}]',
               existing_comment='用户选择的参考图：[{url, label, name, char_version_id?, location_id?}]',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('shot_groups', 'end_frame_description',
               existing_type=sa.TEXT(),
               comment='Phase 3 导演输出的本组终态描述（中文），供下一组参考',
               existing_comment='Phase 3 导演输出的本组终态描述（中文），供下一组生成时参考',
               existing_nullable=True)
    # ### end Alembic commands ###
